server:
  port: 40924

spring:
  application:
    name: service-shiro-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///db_blog?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: root
    # DataSource Config
  redis:
    password: redis
    url: localhost
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/UserMapper.xml
