server:
  port: 40923

spring:
  application:
    name: service-user
  # thymeleaf

#  thymeleaf:
#    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
#    mode: HTML5
#    #编码 可不用配置
#    encoding: UTF-8
#    #内容类别,可不用配置
#    #开发配置为false,避免修改模板还要重启服务器
#    cache: false
#    #配置模板路径，默认是templates，可以不用配置
#    prefix: classpath:/templates/
#    servlet:
#      content-type: text/html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///db_blog?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: root
    # DataSource Config
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
#shiro redis config
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
  cache-maneger:
    expire: 1800
dbdj1201:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: Authorization


#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql:///db_mirror?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&allowPublicKeyRetrieval=true

